#!/usr/bin/env python3
from __future__ import annotations

import argparse
from datetime import datetime
from pathlib import Path


def build_report_content(report_date: str) -> str:
    compact_date = report_date.replace("-", "")
    return f"""# Mobile Real-Device QA Report ({report_date})

- Date: {report_date}
- Tester:
- App commit:
- App URL:
- Notes:

## Device Matrix

| Device | OS version | Browser version | Result (`PASS`/`FAIL`) | Notes |
| --- | --- | --- | --- | --- |
| iOS Safari |  |  |  |  |
| Android Chrome |  |  |  |  |

## Required Checks

Mark each check for each device with `PASS` or `FAIL` and include a short note.

### Modal close + focus behavior

| Device | Backdrop close | Escape/keyboard close | Close button | Logical focus retained | Notes |
| --- | --- | --- | --- | --- | --- |
| iOS Safari |  |  |  |  |  |
| Android Chrome |  |  |  |  |  |

### Narrow-width wrapping (`<= 390px`)

| Device | No overlap/cut-off | No horizontal overflow | Notes |
| --- | --- | --- | --- |
| iOS Safari |  |  |  |
| Android Chrome |  |  |  |

### Tab reachability + selected state

| Device | Tabs reachable | Selected state updates | Notes |
| --- | --- | --- | --- |
| iOS Safari |  |  |  |
| Android Chrome |  |  |  |

### Modal viewport fit

| Device | Controls visible | No horizontal modal scroll | Notes |
| --- | --- | --- | --- |
| iOS Safari |  |  |  |
| Android Chrome |  |  |  |

## Defects

- None / list issues with steps-to-reproduce and screenshots.

## Sign-off

- Overall result (`PASS`/`FAIL`):
- Checklist update:
  - If both devices pass, update `docs/v1-checklist.md` Frontend item 10 to `Complete`.
  - If any device fails, keep item 10 `Pending` and link defect notes.

Generated by `scripts/new_mobile_qa_report.py` on {compact_date}.
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create a dated real-device mobile QA report template.",
    )
    parser.add_argument(
        "--date",
        default=datetime.now().strftime("%Y-%m-%d"),
        help="Report date in YYYY-MM-DD format (default: today).",
    )
    parser.add_argument(
        "--output-dir",
        default="docs/qa-reports",
        help="Directory to write the report template into.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing report file for the same date.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    report_date = args.date
    try:
        datetime.strptime(report_date, "%Y-%m-%d")
    except ValueError:
        raise SystemExit("Invalid --date format. Expected YYYY-MM-DD.")

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    report_path = output_dir / f"mobile-real-device-{report_date.replace('-', '')}.md"

    if report_path.exists() and not args.force:
        raise SystemExit(f"Report already exists: {report_path}")

    report_path.write_text(build_report_content(report_date), encoding="utf-8")
    print(report_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
